apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: main-daemonset
spec:
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: main-container
        image: nginx
